# Generated by Django 2.1.2 on 2018-10-30 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasource', '0003_auto_20181030_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='complaint_link',
            field=models.URLField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='complaint',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
