# Generated by Django 2.1.2 on 2018-10-30 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasource', '0004_auto_20181030_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='last_inspected_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='open_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
